### ISSUE TITLE
Question about logic of pay out winnings

### ISSUE THREAD

**Issue by vux6** [anssip/ultrabet#1]
Hi, 

Cloud you tell me about logic of this TODO:
Check completed field when polling scores. When completed -> set result and pay out winnings

Thanks.

**Comment by anssip** [comment]
The idea is that from the scores feed we get the final result of the event. When we have the final result, we know which bets are winning and which ones lost. Then we can pay out the winning amounts to the players. Paying out actually means increasing the balance in the wallets. 

The process of paying out the winnings has not been implemented yet. 

Is there something else you would like to know about this? @vux6
